basicapp/urls.py
from django.urls import path,re_path
from .views import register, log_in, welcome, log_out
app_name = "basicapp"

urlpatterns = [
    path('register/',register,name="register"),
    path('login/',log_in, name="login"),
    path('welcome/',welcome, name="welcome"),
    path('logout/',log_out, name="logout"),
]

proSix/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("basicapp.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio = models.URLField()
    profile_pic = models.ImageField(upload_to="pro_pics", blank=True)

    def __str__(self):

        return str(self.user)

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserInfo

class UserForm(forms.ModelForm):

    password = forms.CharField(label="Password",widget=forms.PasswordInput())

    class Meta():

        model = User
        fields = ("username","email","password",)

class UserInfoForm(forms.ModelForm):

    class Meta():

        model = UserInfo
        exclude = ("user",)

class LogInForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

basicapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .forms import UserForm,UserInfoForm,LogInForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.
def register(request):

    user = request.user
    user_form = UserForm()
    portfolio_form = UserInfoForm()

    registered = False

    if request.method == "POST":

        user_form = UserForm(data=request.POST)
        portfolio_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and portfolio_form.is_valid():

            user_save = user_form.save()
            user_save.set_password(user_save.password)
            user_save.save()

            portfolio = portfolio_form.save(commit=False)
            portfolio.user = user_save

            if 'profile_pic' in request.FILES:

                portfolio.profile_pic = request.FILES['profile_pic']
                print(request.FILES['profile_pic'])
            
            portfolio.save()

            registered = True

    return render(request, "basicapp/register.html",{'user_form':user_form,'portfolio_form':portfolio_form,'registered':registered,"user":user})

def log_in(request):

    form = LogInForm()
    user = request.user

    if request.method == "POST":

        form = LogInForm(request.POST)

        if form.is_valid():

            user_authenticate = authenticate(username = form.cleaned_data['username'], password = form.cleaned_data["password"])

            if user_authenticate is not None:
                user = user_authenticate
                login(request, user)
                return HttpResponseRedirect(reverse("basicapp:welcome"))

    return render(request, "basicapp/login.html",{'form':form,'user': user})

@login_required
def welcome(request):

    user = request.user
    return render(request, "basicapp/welcome.html",{"user":user})

@login_required
def log_out(request):

    logout(request)
    return HttpResponseRedirect(reverse("basicapp:login"))

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basicapp:register' %}">Register</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basicapp:welcome' %}">Welcome</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basicapp:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basicapp:login' %}">Log In</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <div class="container">
          {% block content %}
          {% endblock %}
      </div>
</body>
</html>

templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block content %}
<div class="jumbotron">
    <h1>Please Login Here</h1>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Log In">
    </form>
</div>
{% endblock %}

templates/basicapp/register.html
{% extends 'basicapp/base.html' %}
{% block content %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thankyou For Registering</h1>
    {% else %}
    <h1>Please Register Here</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ portfolio_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/basicapp/welcome.html
{% extends 'basicapp/base.html' %}
{% block content %}
<h1>Welcome {{ user.username }}</h1>
{% endblock %}